# Assignment Day 3

## Question-1 

1. Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
arr=np.array([x for x in range(2,50,3)])
print(arr)
print(type(arr))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]
<class 'numpy.ndarray'>


## Question-2 

2. Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [9]:
lst1=[]
for i in range(5):
    lst1.append(int(input()))
lst2=[]
for i in range(5):
    lst2.append(int(input()))
arr1=np.array(lst1)
print("Sorted first array",end=" ")
print(np.sort(arr1))
arr2=np.array(lst2)
print("Sorted second array",end=" ")
print(np.sort(arr2))
arr = np.concatenate((arr1, arr2))
print(np.sort(arr))

1
2
5
8
7
9
6
4
2
10
Sorted first array [1 2 5 7 8]
Sorted second array [ 2  4  6  9 10]
[ 1  2  2  4  5  6  7  8  9 10]


## Question-3 

3. Write a code snippet to find the dimensions of a ndarray and its size.

In [16]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(type(ndarray))
print(ndarray.ndim)
print(ndarray.shape)
print(ndarray.size)

<class 'numpy.ndarray'>
2
(3, 3)
9


## Question-4 

4. How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

### np.newaxis : 

In [19]:
onedarray=np.array([1,2,3,4,5,6,7,8,9])
print("Before Conversion",end=" ")
print(onedarray.ndim)
ndarray=onedarray[np.newaxis, :]
print("After Conversion",end=" ")
print(ndarray.ndim)

Before Conversion 1
After Conversion 2


### np.expand_dims : 

In [21]:
onedarray=np.array([1,2,3,4,5,6,7,8,9])
print("Before Conversion",end=" ")
print(onedarray.ndim)
ndarray=np.expand_dims(onedarray,axis=0)
print("After Conversion",end=" ")
print(ndarray.ndim)

Before Conversion 1
After Conversion 2


## Question-5 

5. Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [23]:
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[5, 6], [7, 8]]) 
print("Vertical stacking:\n", np.vstack((arr1, arr2))) 
print("\nHorizontal stacking:\n", np.hstack((arr1, arr2)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


## Question-6 

6. How to get unique items and counts of unique items?

In [24]:
list=np.array([1,1,2,3,4,4,1])
(unique, count)=np.unique(list,return_counts=True)
result=np.asarray((unique,count)).T
print(result)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
